(function() {var implementors = {};
implementors["sorted_vec"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"sorted_vec/struct.SortedVec.html\" title=\"struct sorted_vec::SortedVec\">SortedVec</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a>,&nbsp;</span>",synthetic:true,types:["sorted_vec::SortedVec"]},{text:"impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"sorted_vec/struct.Iter.html\" title=\"struct sorted_vec::Iter\">Iter</a>&lt;'a, T&gt;",synthetic:true,types:["sorted_vec::Iter"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"sorted_vec/struct.IntoIter.html\" title=\"struct sorted_vec::IntoIter\">IntoIter</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a>,&nbsp;</span>",synthetic:true,types:["sorted_vec::IntoIter"]},{text:"impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"sorted_vec/struct.Difference.html\" title=\"struct sorted_vec::Difference\">Difference</a>&lt;'a, T&gt;",synthetic:true,types:["sorted_vec::Difference"]},{text:"impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"sorted_vec/struct.SymmetricDifference.html\" title=\"struct sorted_vec::SymmetricDifference\">SymmetricDifference</a>&lt;'a, T&gt;",synthetic:true,types:["sorted_vec::SymmetricDifference"]},{text:"impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"sorted_vec/struct.Intersection.html\" title=\"struct sorted_vec::Intersection\">Intersection</a>&lt;'a, T&gt;",synthetic:true,types:["sorted_vec::Intersection"]},{text:"impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"sorted_vec/struct.Union.html\" title=\"struct sorted_vec::Union\">Union</a>&lt;'a, T&gt;",synthetic:true,types:["sorted_vec::Union"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
